### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jpmorris** [rsyslog/loganalyzer#13]
Now that loganalyzer is broken in ubuntu 16.04, and with no change to this repo in a year and no version updates on the website for over a year, I'm curious if I have to move to another log analysis software.  Is this project still active?

**Comment by apinchang** [comment]
That guy does not update, I saw this program, is prepared to continue to update
But this program is not very powerful, if you have better can also be recommended.
This article first written in Chinese and then translated into English, the grammar may not pass, please understand, thank you

**Comment by apinchang** [comment]
So, you can issue specific, please?

**Comment by rgerhards** [comment]
yes it is, we just recently had little that needed to be modified. This obviously changed now: https://github.com/rsyslog/loganalyzer/issues/14
