### ISSUE TITLE
add support for php7

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/loganalyzer#14]
There seem to be some issues with php7.

**Comment by apinchang** [comment]
Oh, do not tested PhP7, what's the problem?

**Comment by iceking2nd** [comment]
PHP7 uses mysqli or PDO instead mysql.
So the user system cann't run at PHP7.

**Comment by nacc** [comment]
In Ubuntu 16.04, the issue is two syntax issues: same-named constructor and the use of the \e modifer to preg_replace. I have a patch that fixes both if a PR is acceptable.
