### ISSUE TITLE
install problem with version 4.1.5

### ISSUE THREAD

**Issue by arch7** [rsyslog/loganalyzer#17]
Hi, there is still a problem during the install phase with the new release.
in the install.php file there are still calls to mysql_* API
If I change those 2 calls with the new mysqli_* the install phase locks at the DB discovery (after logging in) with the message
ERROR: Cannot use the database 'loganalyzer'! If the database does not exists, create it or check user access permissions! Mysql Error - Description:

The database is present and the user has all the needed permissions: I can even login with that user in the mysql cli.

I can add that commenting out the lines
`if(!$db_selected) RevertOneStep( $content['INSTALL_STEP']-1, GetAndReplaceLangStr( $content['LN_INSTALL_ERRORACCESSDENIED'], $_SESSION['UserDBName']) . "<br>" . DB_ReturnSimpleErrorMsg());`
it is possible to conclude the installation.

**Comment by st0rmi** [comment]
It might be a good idea to create a minor release for this fix. When trying to install loganalyzer using the latest release tag, I ran into the same problem.

**Comment by st0rmi** [comment]
It might be a good idea to create a minor release for this fix. When trying to install loganalyzer using the latest release tag, I ran into the same problem.

**Comment by vinceroi** [comment]
I ran into the same problem with the latest release 4.1.5 on Debian 9 / MariaDB10.1.26 / Apache/2.4.25 (Debian) / PHP 7.0.19-1
Why this reported issue has been closed?

**Comment by FabioPedretti** [comment]
This was likely closed because it was fixed with 29174ec and 5ae2ddd, however as it was suggested a 4.1.6 release with the fixes would be welcome!

**Comment by rgerhards** [comment]
@alorbach new release sounds like a good idea -- what do you think?

**Comment by alorbach** [comment]
Yes, indeed. I have finalized release 4.1.6.
