### ISSUE TITLE
Absolute paths prevent usage behind a reverse proxy

### ISSUE THREAD

**Issue by joernott** [rsyslog/loganalyzer#21]
I set up loganalyzer on an internal host (to be precise, in a docker container) and want to expose it to the developers in a folder on the management reverse proxy. This works and I can access various pages via the browser. For example, accessing events of the first log source via the "Show events" button works fine because the URL there is "./index.php" . When using the dropdown to select a different log source, the browser tries to open /index.php instead, which fails in the reverse proxy setup. The same goes for other pages like search, too.

This can be solved by changing line 125 in include/functions_frontendhelpers.php to

`$content['CURRENTURL'] = ltrim($_SERVER['PHP_SELF'],'/');`

**Comment by alorbach** [comment]
In order to support other URL's like the one automatically generated internally using PHP_SELF, we would need to implement a setting to overwrite the base url. That would also solve issues like this.

**Comment by spacecabbie** [comment]
Its an older issue but reading this I cannot help it that the prox has been incorrectly setup. For I have many times set up. every time i had run into issue it was the proxy not properly configured trailing / for example in location directive, cause 404 errors and dead links. 
Just trowing it out as a suggestion.
