### ISSUE TITLE
loganalyzer-4.1.7 'Add new Field' ERROR 

### ISSUE THREAD

**Issue by liaoqiArno** [rsyslog/loganalyzer#28]
I want add client IP to my loganalyzer.
[http://www.ituring.com.cn/article/128536](url) ,I  consulted this website.
but when I   'Add new Field',the loganalyzer  Error
![image](https://user-images.githubusercontent.com/29945921/58221193-3d3a7480-7d44-11e9-9439-9d3b7e1a8402.png)

`Dataquery failed to execute

Database error: Invalid SQL: INSERT INTO SystemEventsfields (FieldID, FieldCaption, FieldDefine, SearchField, FieldAlign, DefaultWidth, FieldType, SearchOnline) VALUES ( 'FromIp', 'IP', 'SYSLOG_FROMIP', 'source', 'center', 50, 0, false ) 
mysql error: Field 'Sortable' doesn't have a default value 
mysql error number: 1364 
Date: 23.05.2019 @ 10:17
Script: /admin/fields.php
Referer: http://172.17.11.21/admin/fields.php?op=add`

`mysql> desc SystemEventsfields;
+--------------+--------------+------+-----+---------+-------+
| Field        | Type         | Null | Key | Default | Extra |
+--------------+--------------+------+-----+---------+-------+
| FieldID      | varchar(64)  | NO   | PRI | NULL    |       |
| FieldDefine  | varchar(64)  | NO   |     | NULL    |       |
| FieldCaption | varchar(255) | NO   |     | NULL    |       |
| FieldType    | int(11)      | NO   |     | NULL    |       |
| Sortable     | tinyint(1)   | NO   |     | NULL    |       |
| DefaultWidth | int(11)      | NO   |     | NULL    |       |
| FieldAlign   | varchar(32)  | NO   |     | NULL    |       |
| SearchField  | varchar(64)  | NO   |     | NULL    |       |
| SearchOnline | tinyint(1)   | NO   |     | NULL    |       |
| Trunscate    | int(11)      | NO   |     | NULL    |       |
+--------------+--------------+------+-----+---------+-------+
`

HOW  add others column?

**Comment by alorbach** [comment]
Its an sql table problem. Set a default for the field "Sortable", with this SQL: 

ALTER TABLE `tableprefix_fields` CHANGE `Sortable` `Sortable` TINYINT(1) NOT NULL DEFAULT '0';

**Comment by ChunshengZhao** [comment]
The same problem occurs in the process of creating a new field:

//
Critical Error occured
Errordetails:	
Automatic redirect to the page was aborted, as an internal error occured. Please see the error details above and contact our support forums if you need assistance.

Additional Errordetails:	
Dataquery failed to execute

Database error: Invalid SQL: INSERT INTO logcon_fields (FieldID, FieldCaption, FieldDefine, SearchField, FieldAlign, DefaultWidth, FieldType, SearchOnline) VALUES ( 'FROMIP', 'FromIP', 'SYSLOG_FROMIP', 'source', 'left', 60, 0, false )
mysql error: Field 'Trunscate' doesn't have a default value
mysql error number: 1364
Date: 04.07.2020 @ 08:44
Script: /admin/fields.php
Referer: http://<IP>/admin/fields.php?op=add
//

Solution:
ALTER TABLE logcon_fields CHANGE Trunscate Trunscate int(11) NOT NULL DEFAULT '0';
