### ISSUE TITLE
Can't Delete source data

### ISSUE THREAD

**Issue by 88fingerslukee** [rsyslog/loganalyzer#29]
v4.1.7

I get the following error when selecting "remove old data records"

Could not delete data in the '1' source

any thoughts?

![image](https://user-images.githubusercontent.com/2788639/58720164-42bc3e00-8386-11e9-91b4-7e74d25784da.png)

**Comment by alorbach** [comment]
Does your database user have sufficient rights to delete records in your table?

**Comment by 88fingerslukee** [comment]
> Does your database user have sufficient rights to delete records in your table?

Apologies, I should have stated that in the original post. Yes, I have tried it with a fully authorized user as well as the root user. It doesn't work either way. Also, I'm not entirely sure how to get a log of loganylzer's activities.

**Comment by 88fingerslukee** [comment]
Here is my Source settings page

![image](https://user-images.githubusercontent.com/2788639/58814014-ce79d880-85d9-11e9-867f-5e692c8d7cdc.png)

**Comment by 88fingerslukee** [comment]
@alorbach Any thoughts on this? Where does the application output its logs to? Shouldn't it be throwing up some sort of error?

**Comment by alorbach** [comment]
Sorry for the delay. 
can you check that box for debug output and see what it prints on bottom loganalyzer page? 
![image](https://user-images.githubusercontent.com/1675286/65700174-7af73300-e07f-11e9-8213-8f3350f6b354.png)

**Comment by 88fingerslukee** [comment]
It doesn't print anything.

![image](https://user-images.githubusercontent.com/2788639/65703625-f2a26f00-e039-11e9-97cc-513bcbc4d505.png)

**Comment by spacecabbie** [comment]
> It doesn't print anything.
> 
> ![image](https://user-images.githubusercontent.com/2788639/65703625-f2a26f00-e039-11e9-97cc-513bcbc4d505.png)

I have tested this under 4.1.8 it works flawlessly could you try updating and see if the issue still perisist ?

**Comment by 88fingerslukee** [comment]
> I have tested this under 4.1.8 it works flawlessly could you try updating and see if the issue still perisist ?

It's still happening. I simply don't understand.

**Comment by 88fingerslukee** [comment]
@alorbach @spacecabbie Can you please tell me what linux and MySQL versions you guys are using?

mysql  Ver 15.1 Distrib 10.1.43-MariaDB
Ubuntu 18.04.3 LTS

**Comment by spacecabbie** [comment]
I'll get you that asap I change system for production quite busy i am setting up a test environment to continue working on loganalyzer in the background. give me a couple of days.

Ps does anyone know a way of simulating log output ?

**Comment by jerrylu2008** [comment]
I found a solution. Add "InitSource($tmpSource);" after line 357. Hope it helps you.

  // --- Init the source
                        $tmpSource = $content['Sources'][ $content['SOURCEID'] ];
                        **InitSource($tmpSource);**

**Comment by 88fingerslukee** [comment]
Holy freaking crap. Thank you sooooo much!! @jerrylu2008 You're a champion.

Can somebody please add this as a fix?
