### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_insert_id() in /var/www/html/loganalyzer/admin/reports.php:1158

### ISSUE THREAD

**Issue by eduardocalfaia** [rsyslog/loganalyzer#30]
Hi Guys,
I've changed mysql_insert_id() by the mysqli_insert_id() in reports.php and I've gotten the error bellow. The sourceid field  is integer in mysql, the app is putting the string "Source1".

Dataquery failed to execute

Database error: Invalid SQL: INSERT INTO logcon_savedreports (reportid, sourceid, customTitle, customComment, filterString, customFilters, outputFormat, outputTarget, outputTargetDetails, scheduleSettings) VALUES ('auditsummary', Source1, 'EventLog Audit Summary Report', '', '', '_maxHosts=>20, _maxauditsummarysPerHost=>100, _colorThreshold=>10, _events_logon=>1, _events_logoff=>1, _events_logonfail=>1, _events_policychangeevents=>1, _events_objectaccess=>1, _events_systemevents=>1, _events_hostsessionevents=>1, _events_useraccchangeevents=>1, _events_auditpolicychangesevents=>1, _events_useractions=>1, _events_hostactions=>1', 'html', 'stdout', 'filename=>,', '' ) 
mysql error: Unknown column 'Source1' in 'field list' 
mysql error number: 1054 
Date: 29.07.2019 @ 12:30
Script: /loganalyzer/admin/reports.php?op=addsavedreport&id=auditsummary
Referer: http://192.168.1.133/loganalyzer/admin/reports.php?op=addsavedreport&id=auditsummary

Thanks in advance

**Comment by GOGradus** [comment]
There missing single quotes on the value 'Source1' in the sql query.

**Comment by rgerhards** [comment]
@alorbach can you do a quick fix?

**Comment by alorbach** [comment]
Ì will look into this

**Comment by eduardocalfaia** [comment]
Thanks @alorbach

**Comment by eduardocalfaia** [comment]
Thanks @rgerhards
