### ISSUE TITLE
error in PHP 7.3

### ISSUE THREAD

**Issue by damionx7** [rsyslog/loganalyzer#31]
<img width="762" alt="Screenshot 2019-07-31 at 12 46 27 PM" src="https://user-images.githubusercontent.com/6530843/62191514-3dcd3800-b391-11e9-95fb-4c3cdf1f4a57.png">

I get the above error while using Adiscon LogAnalyzer

<img width="192" alt="Screenshot 2019-07-31 at 12 46 56 PM" src="https://user-images.githubusercontent.com/6530843/62191548-50477180-b391-11e9-89b1-6aea96756e4c.png">

**Comment by eduardocalfaia** [comment]
Hi @damionx7 
I think that is only a warning.

**Comment by damionx7** [comment]
Ok 👍

**Comment by damionx7** [comment]
I think you guys should update it for php7.3

**Comment by alorbach** [comment]
We haven't checked it against PHP 7.3 yet.
