### ISSUE TITLE
Reports don't display Syslogmessages consolidated per Host inside reports

### ISSUE THREAD

**Issue by GOGradus** [rsyslog/loganalyzer#32]
In the older version of loganalyzer, running on PHP 5.5, we getting a nice list of "Syslogmessages consolidated per Host" in the reports.
On the newest version of loganalyzer, running op PHP 7.0, the list is empty.

The report summery shows that there are issues, but the are not showed in the report anymore.

Reports got the same configuration on both instances.

**Comment by alorbach** [comment]
Can you post those issues ?

**Comment by GOGradus** [comment]
I've found the issue.
One of the queries don't work with a mysql strict configuration.
So i've changed the mysql config, and now it works fine.
