### ISSUE TITLE
SourceID Error

### ISSUE THREAD

**Issue by eduardocalfaia** [rsyslog/loganalyzer#33]
Hi All,
I have updated to 4.1.8 to fix the issue "Reports Admin: fixed insert sql statement for savereports (SourceID)."
However, I am getting the same error.
Does anyone have some clarity about that?

Thanks

**Comment by spacecabbie** [comment]
I can confirm partly that errors are trown when generating reports:
> Database error: Invalid SQL: INSERT INTO logcon_savedreports (reportid, sourceid, customTitle, customComment, filterString, customFilters, outputFormat, outputTarget, outputTargetDetails, scheduleSettings) VALUES ('auditsummary', 'Source1', 'EventLog Audit Summary Report', '', '', '_maxHosts=>20, _maxauditsummarysPerHost=>100, _colorThreshold=>10, _events_logon=>1, _events_logoff=>1, _events_logonfail=>1, _events_policychangeevents=>1, _events_objectaccess=>1, _events_systemevents=>1, _events_hostsessionevents=>1, _events_useraccchangeevents=>1, _events_auditpolicychangesevents=>1, _events_useractions=>1, _events_hostactions=>1', 'html', 'stdout', 'filename=>,', '' )
mysql error: Incorrect integer value: 'Source1' for column `Syslog`.`logcon_savedreports`.`sourceid` at row 1
mysql error number: 1366
Date: 20.12.2019 @ 08:58
Script: /loganalyzer/admin/reports.php?op=addsavedreport&id=auditsummary
Referer: https://vps.spacecabbie.nl/loganalyzer/admin/reports.php?op=addsavedreport&id=auditsummary&optimize=indexes

This is above what i can fix so you'll have to wait for a expert to drop by

**Comment by spacecabbie** [comment]
More debug:
Basicaly its around the sourceid value I get 2 variants 1. where on initial creation a sourceid was not set and every update afther that fails (no such value) although i manged to repair that one i think see: [this patch](https://github.com/rsyslog/loganalyzer/compare/master...spacecabbie:patch-1)
This query has error: 

> sourceid = ,

 it should be 

> sourceid = '',

```Dataquery failed to execute

Database error: Invalid SQL: UPDATE logcon_savedreports SET sourceid = , customTitle = 'EventLog Summary Report', customComment = '', filterString = 'severity:=EMERG severity:=ALERT uID:=2 ', customFilters = '_maxHosts=>20, _maxEventsPerHost=>100, _colorThreshold=>10', outputFormat = 'html', outputTarget = 'stdout', outputTargetDetails = 'filename=>,', scheduleSettings = '' WHERE ID = 5
mysql error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' customTitle = 'EventLog Summary Report', customComment = ''' at line 2
mysql error number: 1064
Date: 22.12.2019 @ 15:06
Script: /loganalyzer/admin/reports.php?op=editsavedreport&id=eventsummary&savedreportid=5
Referer: `https://vps.spacecabbie.nl/loganalyzer/admin/reports.php?op=editsavedreport&id=eventsummary&savedreportid=5```

**Comment by rgerhards** [comment]
@alorbach maybe a quick fix?

**Comment by alorbach** [comment]
has been fixed by https://github.com/rsyslog/loganalyzer/pull/40
