### ISSUE TITLE
Links to old documentation offline.

### ISSUE THREAD

**Issue by spacecabbie** [rsyslog/loganalyzer#35]
Reformed the post into Feature. (old post below.)

Todo list:
1. remap links to domains and/or ip's to whois site 
2. remap the oracle. 
3. remap dynamic generated links to wiki.
4. while where on it create help tooltips.
5...... suggestions ?

> Hello and Greetings,
> 
> Allot of the Help links are dead:
> http://kb.monitorware.com/phplogcon-f39.html <--- grdp
> http://wiki.rsyslog.com/index.php/PhpLogCon_FAQ <-- error
> http://loganalyzer.adiscon.com/doc-professional_services.html <-- not found
> http://kb.monitorware.com/search.php <--- grdp
> 
> Also a lot of generated links when clicking on search results etc.
> The monitorware site seems to be the most important since almost everything is linking there.
> The have been removed due to GRDP issues i was wondering how can I help to update this ? I am basic coder but changing links shouldn't be difficult
> 
> I would suggest if someone has access to backups to convert it all to a build-in wiki here at github ?
> Any ways new here so let me know If and how I could help out.

**Comment by rgerhards** [comment]
FYI: the doc source is hosted right here: https://github.com/rsyslog/loganalyzer/tree/master/doc 

At least in theory it should propagate via nightly build to the web site.

The wiki is gone for 2 years now I think and IIRC it had very little info on loganalyzer (and a large lot of spam). Not sure if someone still has a backup.

**Comment by spacecabbie** [comment]
> FYI: the doc source is hosted right here: https://github.com/rsyslog/loganalyzer/tree/master/doc
> 
> At least in theory it should propagate via nightly build to the web site.
Yes 
> 
> The wiki is gone for 2 years now I think and IIRC it had very little info on loganalyzer (and a large lot of spam). Not sure if someone still has a backup.

The wiki was quite useless (waybackmachine) :) But its the forum the dynamic links go to mainly.
http://kb.monitorware.com/phplogcon-f39.html etc.
If its possible to recover those dumb the sql table or something then its quite easy to get em converted to a wiki based and relink those and voila. And asfaik since the wiki is here a github the gdrp has no impact ? (I really need to read that that Shit... (eh irritating law yea lets go with that), is about.

Then remove the links to forum/wiki fix the professional services link and voila.
If you agree with this by all means open up the wiki for this project here and see if you can get me a sql file and i'll do all this (will take me some time bussy and stuff but gladly do its since loganalyzer safed me a couple of days work.

**Comment by rgerhards** [comment]
I checked. There exist no backups. This is actually intentional, as the GDPR prohibits such backups without getting prior user permission. That, in turn, was one of the original problems with the GDPR. So we deleted everything where we could not get that permission with sufficient effort.

**Comment by rgerhards** [comment]
> And asfaik since the wiki is here a github the gdrp has no impact ?

It's slippery slope. It would be best if a third party would set one up.

**Comment by spacecabbie** [comment]
Okay I am a bit confused I have had time to read up on the GDRP. It's all about user content en information. A wiki is user generated and if the info there is removable upon request we should be save.
I am wondering tbh why the forum was a risk ? Unless a user asks for his account to be deleted and its refused then there is an issue. Unless I am completely off here.

But I managed to find a backup it's actually just links to posts made by admins zie example below.
IMHO that should be save to dump into a small wiki. If there is truly a risk. Then lets just include it as documentation within loganalyzer, with links to google search. .
Any ways i got the information.  Now if you suggest where we could place it then where off.
I am perfectly happy creating and filling a wikki and redirect all the links.  we just need to decide where :)

`KnowledgeBase Event Repository
This site is the central interface to the Adiscon Event Repository

ERROR IDITEMS COUNTACCESS COUNT
1
Generic Error11000Views
2
File could not be found15173Views
3
Can't close File1729Views
4
End of File reached1689Views
5
Begin of File reeached1765Views
6
Undefined Error1653Views
7
End of stream reached1666Views
8
No more records found174286Views
9
Filter does not match any results1686Views`

**Comment by rgerhards** [comment]
> A wiki is user generated and if the info there is removable upon request we should be save.
> I am wondering tbh why the forum was a risk ? Unless a user asks for his account to be deleted and its refused then there is an issue. Unless I am completely off here.

you need to read the fine print, as always in legal. Under our jurisdiction, e.g., a small failure can lead to a so-called "abmahnung" (letter of decise, I think), which will come with a cost of potentially several thousand dollars. This needs to be paid even if you follow the request. Also, you need to have advance permission, which nobody had for pre-gdpr conent. also, the system must support exporting and deleting the user content at request (which the forum did not do and I think the wiki only partly). Also, you need to think about copyright if you use the content without users name and permission, Also...

That said: how about if you clone the repositiory and run the wiki yourself? The official doc could than link to your wiki. Does that sound doable?

**Comment by spacecabbie** [comment]
Sure np just wanted to avoid confusion :)  But here it is: https://github.com/spacecabbie/loganalyzer-doc
I will be filling the wiki with any content i can find. I have added an disclaimer on the wiki witch I have checked it should in theory be ok. I have some questions outstanding to some old friends (lawyers) who hopefully the can help me come up with a perfect disclaimer.

I like to when i have edit basic content and readjust the links in log analyzer create a small notice in loganalyer for the next public version linking to the wiki so we can get hopefully a bit more contributors. the main repository i can copy the documentation there as wel for editing and maintance or do we keep those at the original repo ?

**Comment by rgerhards** [comment]
> y i can copy the documentation there as wel for editing and maintance or do we keep those at the original repo ?

The doc needs to stay with the main project, else it gets very confusing for users. But as you know we accept PRs for the repo. Adding appropriate links to your wiki is welcome.

**Comment by spacecabbie** [comment]
@rgerhards @alorbach 

Could i bother either one of you to give me a quick walkthrough of structure in log analyzer.
I am looking for something similar like: https://github.com/chamilo/chamilo-lms/wiki/Coding-conventions Ofc that extreamly extensive but roughly guideline so i know where to edit what.

I have had time to go through basic code and i like to do allot more since this is code I quite understand.

**Comment by rgerhards** [comment]
@spacecabbie FYI: I know very little about the code, was involved in the design I guess around 10 yrs ago. @alorbach will probably not reply this week.

**Comment by spacecabbie** [comment]
> @spacecabbie FYI: I know very little about the code, was involved in the design I guess around 10 yrs ago. @alorbach will probably not reply this week.

Ah np din't expect an answer from any one tbh until next "year" Frohe Weihnachten. :)
First patches are in. Currently working on the oracly to redirect everything. I am still planning stuff but I might turn the wiki into a website like http://www.eventid.net/ there is nothing like it for nix systems. 

Ps. while i have you, I did a var_dump on $content variable in loganalyzer. That dumped literally everything from the db it looks like (content wise not logging). Isn't that excessive ? and would slow everything down ? From what i can see on other projects is that it's all stored in seperate arrays and then only those are called per page. I am learning as i go for the past 2 years so I have had no education to know what is "standard"

**Comment by rgerhards** [comment]
> Ps. while i have you, I did a var_dump on $content variable in loganalyzer. That dumped literally everything from the db it looks like (content wise not logging). Isn't that excessive ? and would slow everything down ? From what i can see on other projects is that it's all stored in seperate arrays and then only those are called per page. I am learning as i go for the past 2 years so I have had no education to know what is "standard"

I cannot comment on this. As I said: I know almost nothing about the actual code. I am also far from a php wiz ;-)

**Comment by spacecabbie** [comment]
>> I cannot comment on this. As I said: I know almost nothing about the actual code. I am also far from a php wiz ;-)

OH well no short cuts then this time 👍 i'll have to jump into some documentations.

**Comment by spacecabbie** [comment]
I am really sorry but with everything i have going on I do not have enough time to dedicate to this. My php knowledge is just not enough for this scale yet I am afraid. I'll have to put it on low priority for now sorry.
