### ISSUE TITLE
wrong file name reference

### ISSUE THREAD

**Issue by N1ghtshad0w** [rsyslog/loganalyzer#44]
I got an error when I switched my logs to the syslog23 format
`Couldn't locate LineParser include file './classes/logstreamlineparserSyslog23.class.php'`
to fix it
`cp logstreamlineparsersyslog23.class.php logstreamlineparserSyslog23.class.php`

**Comment by alorbach** [comment]
filenames are case sensitive, I think your configured "Syslog23" instead of "syslog23" as format.
