### ISSUE TITLE
Loganalyzer requires mysql_ libraries

### ISSUE THREAD

**Issue by jeroenrnl** [rsyslog/loganalyzer#9]
After installation, one can use the PDO driver, but during installation (install.php) the mysql_ drivers are still user, which are not available anymore since PHP 5.6

**Comment by jeroenrnl** [comment]
I found out that the loganalyzer in fact does need mysql_ even after install, the DB_Connect function calls it...

**Comment by jpmorris** [comment]
mysql_connect() (and probably others) are not in Ubuntu 16.04 (since they moved to php 7.0 which depreciated these functions) and now loganalyzer is broken.

**Comment by alorbach** [comment]
Loganalyzer has not been tested with php7 yet. After a quick test I see other issues which need to be solved.

**Comment by rgerhards** [comment]
added a new issue for php7: https://github.com/rsyslog/loganalyzer/issues/14
