### ISSUE TITLE
Need some help with nginx access.log

### ISSUE THREAD

**Issue by ambipur76** [rsyslog/loganalyzer#95]
I am experiencing problems displaying Date, Host, URL, User
Agent, Status and Bytes Sent columns, only the Message column contains data.
My Loganalyzer version is 4.1.13. Related fragment of my Loganalyzer config.php:

`$CFG['Sources']['Source6']['ID'] = "Source6";

$CFG['Sources']['Source6']['Name'] = "Nginx access log";

$CFG['Sources']['Source6']['ViewID'] = "WEBLOG";

$CFG['Sources']['Source6']['SourceType'] = SOURCE_DISK;

$CFG['Sources']['Source6']['MsgParserList'] = "apache2";

$CFG['Sources']['Source6']['LogLineType'] = "syslog";

$CFG['Sources']['Source6']['DiskFile'] = "/var/log/nginx/access.log";
`
I have tried to use both single and double quotes. I have configured nginx logging in the following way:

`
log_format analytics '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent $query_string '
                             '"$http_referer" "$http_user_agent" '
                             '"$geoip_country_code, $geoip_city_country_name, $geoip_city, $geoip_postal_code"';
        access_log /var/log/nginx/access.log analytics;
`

Could you give me some hints? Do I have something misconfigured?

**Comment by alorbach** [comment]
You will have to write your own logfile parser in order to read nginx access logs in that format.
As this is custom development you may take a look here: 
https://loganalyzer.adiscon.com/support/custom-development/

**Comment by ambipur76** [comment]
Fortunately I have found a much simpler method. I have modified my nginx access log format:
`
log_format analytics '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$geoip_country_code, $geoip_city_country_name, $geoip_city, $geoip_postal_code $http_user_agent"';
        access_log /var/log/nginx/access.log analytics;
`
This way the geoip data are added in front of the user agent string, which from my point of view is not so important. In Loganalyzer appears correctly in the User Agent column. That's all folks! :)
